[project]
name = "del-y-subs"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Peter Schwenk", email = "paschwenk@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "textual>=8.2.8",
]

[project.scripts]
del-y-subs = "del_y_subs:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "textual[dev]>=8.2.8",
]
